spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ssm_forum?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  error:
    include-message: always
    include-exception: true
  port: 8080

logging:
  level:
    com.lmj.forum.dao: debug
